In [25]:
import pandas as pd

In [88]:
df = pd.read_csv('lecture01_bacterial_expression.csv',sep=",")
df.head(3)

  sample_id species treatment  gene_a  gene_b  gene_c  growth_rate   response
0       S01  E_coli   control     5.1     2.0     7.2         0.91  sensitive
1       S02  E_coli      drug     8.2     3.8     6.1         0.42  resistant
2       S03  E_coli   control     5.5     2.2     7.0         0.88  sensitive

In [35]:
df = pd.read_csv('lecture01_bacterial_expression.tsv',sep='\t')
df.head(3)

  sample_id species treatment  gene_a  gene_b  gene_c  growth_rate   response
0       S01  E_coli   control     5.1     2.0     7.2         0.91  sensitive
1       S02  E_coli      drug     8.2     3.8     6.1         0.42  resistant
2       S03  E_coli   control     5.5     2.2     7.0         0.88  sensitive

In [41]:
df = pd.read_excel('lecture01_bacterial_expression.xlsx')
df

,sample_id,species,treatment,gene_a,gene_b,gene_c,growth_rate,response
0,S01,E_coli,control,5.1,2.0,7.2,0.91,sensitive
1,S02,E_coli,drug,8.2,3.8,6.1,0.42,resistant
2,S03,E_coli,control,5.5,2.2,7.0,0.88,sensitive
3,S04,E_coli,drug,9.0,4.1,5.8,0.35,resistant
4,S05,B_subtilis,control,4.8,2.7,8.0,0.82,sensitive
5,S06,B_subtilis,drug,7.1,3.5,6.9,0.51,resistant
6,S07,B_subtilis,control,4.9,2.5,8.1,0.85,sensitive
7,S08,B_subtilis,drug,7.6,3.9,6.5,0.47,resistant
8,S09,E_coli,drug,8.5,4.0,6.0,0.39,resistant
9,S10,E_coli,control,5.2,2.1,7.3,0.90,sensitive
10,S11,B_subtilis,drug,NaN,3.7,6.7,0.49,resistant
11,S12,B_subtilis,control,4.7,2.6,8.2,0.87,sensitive

In [40]:
df.shape

(12, 8)

In [44]:
df.columns

Index(['sample_id', 'species', 'treatment', 'gene_a', 'gene_b', 'gene_c',
       'growth_rate', 'response'],
      dtype='object')

In [45]:
df.index

RangeIndex(start=0, stop=12, step=1)

In [46]:
df.dtypes

sample_id       object
species         object
treatment       object
gene_a         float64
gene_b         float64
gene_c         float64
growth_rate    float64
response        object
dtype: object

In [26]:
# 2, 1, 17 - intergers
# 2.5, 0.3, 9.2, 3.0 - floats

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sample_id    12 non-null     object
 1   species      12 non-null     object
 2   treatment    12 non-null     object
 3   gene_a       11 non-null     float64
 4   gene_b       12 non-null     float64
 5   gene_c       12 non-null     float64
 6   growth_rate  12 non-null     float64
 7   response     12 non-null     object
dtypes: float64(4), object(4)
memory usage: 900.0+ bytes

In [49]:
df.isna().sum()

sample_id      0
species        0
treatment      0
gene_a         1
gene_b         0
gene_c         0
growth_rate    0
response       0
dtype: int64

In [50]:
df.describe()

          gene_a     gene_b     gene_c  growth_rate
count  11.000000  12.000000  12.000000    12.000000
mean    6.418182   3.091667   6.983333     0.655000
std     1.672614   0.811797   0.818905     0.231222
min     4.700000   2.000000   5.800000     0.350000
25%     5.000000   2.425000   6.400000     0.457500
50%     5.500000   3.100000   6.950000     0.665000
75%     7.900000   3.825000   7.475000     0.872500
max     9.000000   4.100000   8.200000     0.910000

In [51]:
df.head()

,sample_id,species,treatment,gene_a,gene_b,gene_c,growth_rate,response
0,S01,E_coli,control,5.1,2.0,7.2,0.91,sensitive
1,S02,E_coli,drug,8.2,3.8,6.1,0.42,resistant
2,S03,E_coli,control,5.5,2.2,7.0,0.88,sensitive
3,S04,E_coli,drug,9.0,4.1,5.8,0.35,resistant
4,S05,B_subtilis,control,4.8,2.7,8.0,0.82,sensitive

In [60]:
df.loc[(df['response'] != 'sensitive') | (df['species'] == 'E_coli')]

,sample_id,species,treatment,gene_a,gene_b,gene_c,growth_rate,response
0,S01,E_coli,control,5.1,2.0,7.2,0.91,sensitive
1,S02,E_coli,drug,8.2,3.8,6.1,0.42,resistant
2,S03,E_coli,control,5.5,2.2,7.0,0.88,sensitive
3,S04,E_coli,drug,9.0,4.1,5.8,0.35,resistant
5,S06,B_subtilis,drug,7.1,3.5,6.9,0.51,resistant
7,S08,B_subtilis,drug,7.6,3.9,6.5,0.47,resistant
8,S09,E_coli,drug,8.5,4.0,6.0,0.39,resistant
9,S10,E_coli,control,5.2,2.1,7.3,0.90,sensitive
10,S11,B_subtilis,drug,NaN,3.7,6.7,0.49,resistant

In [40]:
df.loc[df['species'] == 'E_coli']

  sample_id species treatment  gene_a  gene_b  gene_c  growth_rate   response
0       S01  E_coli   control     5.1     2.0     7.2         0.91  sensitive
1       S02  E_coli      drug     8.2     3.8     6.1         0.42  resistant
2       S03  E_coli   control     5.5     2.2     7.0         0.88  sensitive
3       S04  E_coli      drug     9.0     4.1     5.8         0.35  resistant
8       S09  E_coli      drug     8.5     4.0     6.0         0.39  resistant
9       S10  E_coli   control     5.2     2.1     7.3         0.90  sensitive

In [41]:
df.loc[df['response'] == 'sensitive']

,sample_id,species,treatment,gene_a,gene_b,gene_c,growth_rate,response
0,S01,E_coli,control,5.1,2.0,7.2,0.91,sensitive
2,S03,E_coli,control,5.5,2.2,7.0,0.88,sensitive
4,S05,B_subtilis,control,4.8,2.7,8.0,0.82,sensitive
6,S07,B_subtilis,control,4.9,2.5,8.1,0.85,sensitive
9,S10,E_coli,control,5.2,2.1,7.3,0.90,sensitive
11,S12,B_subtilis,control,4.7,2.6,8.2,0.87,sensitive

In [69]:
df.to_excel('test_save.xlsx',index=False)

In [73]:
#extracting columns
df1 = df[['sample_id','gene_a','growth_rate']]
df1.head()

  sample_id  gene_a  growth_rate
0       S01     5.1         0.91
1       S02     8.2         0.42
2       S03     5.5         0.88
3       S04     9.0         0.35
4       S05     4.8         0.82

In [77]:
df['gene_a'].mean()

np.float64(6.418181818181818)

In [78]:
df['gene_a'].std()

np.float64(1.672613632503443)

In [80]:
df.head()

,sample_id,species,treatment,gene_a,gene_b,gene_c,growth_rate,response
0,S01,E_coli,control,5.1,2.0,7.2,0.91,sensitive
1,S02,E_coli,drug,8.2,3.8,6.1,0.42,resistant
2,S03,E_coli,control,5.5,2.2,7.0,0.88,sensitive
3,S04,E_coli,drug,9.0,4.1,5.8,0.35,resistant
4,S05,B_subtilis,control,4.8,2.7,8.0,0.82,sensitive

In [83]:
df.sort_values(by='gene_b',ascending=False).head()

,sample_id,species,treatment,gene_a,gene_b,gene_c,growth_rate,response
3,S04,E_coli,drug,9.0,4.1,5.8,0.35,resistant
8,S09,E_coli,drug,8.5,4.0,6.0,0.39,resistant
7,S08,B_subtilis,drug,7.6,3.9,6.5,0.47,resistant
1,S02,E_coli,drug,8.2,3.8,6.1,0.42,resistant
10,S11,B_subtilis,drug,NaN,3.7,6.7,0.49,resistant

In [85]:
#df.drop_duplicates('species',ignore_index=True)

,sample_id,species,treatment,gene_a,gene_b,gene_c,growth_rate,response
0,S01,E_coli,control,5.1,2.0,7.2,0.91,sensitive
1,S05,B_subtilis,control,4.8,2.7,8.0,0.82,sensitive

In [99]:
df = pd.read_csv('lecture01_bacterial_expression.csv',sep=",")

df2 = df[['species','gene_a']]
df2.head()

      species  gene_a
0      E_coli     5.1
1      E_coli     8.2
2      E_coli     5.5
3      E_coli     9.0
4  B_subtilis     4.8

In [103]:
df.groupby('species',as_index=False,sort=False).count()

,species,sample_id,treatment,gene_a,gene_b,gene_c,growth_rate,response
0,E_coli,6,6,6,6,6,6,6
1,B_subtilis,6,6,5,6,6,6,6